server {
    listen 443 ssl;
    server_name nextcloud.ignacio.asir;

    ssl_certificate     /etc/ssl/nginx/ignacio.asir.crt;
    ssl_certificate_key     /etc/ssl/nginx/ignacio.asir.key;

    location / {
        proxy_pass https://10.255.212.60:1443;
    }
}

server {
    listen 443 ssl;
    server_name jellyfin.ignacio.asir;

    ssl_certificate     /etc/ssl/nginx/ignacio.asir.crt;
    ssl_certificate_key     /etc/ssl/nginx/ignacio.asir.key;

    location / {
        proxy_pass http://10.255.212.60:8096;
    }
}

server {
    listen 443 ssl;
    server_name duplicati.ignacio.asir;

    ssl_certificate     /etc/ssl/nginx/ignacio.asir.crt;
    ssl_certificate_key     /etc/ssl/nginx/ignacio.asir.key;

    location / {
        proxy_pass http://10.255.212.60:8200;
    }
}

server {
    listen 443 ssl;
    server_name calibre.ignacio.asir;

    ssl_certificate     /etc/ssl/nginx/ignacio.asir.crt;
    ssl_certificate_key     /etc/ssl/nginx/ignacio.asir.key;

    location / {
        proxy_pass http://10.255.212.60:8083;
    }
}
server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
