server {
    listen 80;
    server_name nextcloud.ignacio.asir;

    location / {
        proxy_pass https://10.255.212.60:1443;
    }
}

server {
    listen 80;
    server_name jellyfin.ignacio.asir;

    location / {
        proxy_pass http://10.255.212.60:8096;
    }
}

server {
    listen 80;
    server_name duplicati.ignacio.asir;

    location / {
        proxy_pass http://10.255.212.60:8200;
    }
}

server {
    listen 80;
    server_name calibre.ignacio.asir;

    location / {
        proxy_pass http://10.255.212.60:8083;
    }
}
