server {
    listen 80;
    server_name ignacio.asir;

    location /nextcloud {
        proxy_pass https://10.255.212.60:1443/;
    }

    location /jellyfin {
        proxy_pass http://10.255.212.60:8096/;
    }

    location /duplicati {
        proxy_pass http://10.255.212.60:8200/;
    }

    location /calibre {
        proxy_pass http://10.255.212.60:8083/;
    }
}
